export const CONFIG = {
  SCHEMA_VERSION: 1,
  EXPORT_VERSION: 3,
  STORAGE_KEYS: {
    WORKSPACES: 'tabmind_workspaces',
    META: 'tabmind_schema_meta',
    SORT_PREFERENCE: 'tabmind_sort_preference',
    AI_SETTINGS: 'tabmind_ai_settings',
    PREFERENCE_MEMORY: 'tabmind_preference_memory',
  },
  SORT_OPTIONS: {
    NEWEST: 'newest',
    OLDEST: 'oldest',
    AZ: 'az',
    ZA: 'za',
    MOST_TABS: 'most_tabs',
    LEAST_TABS: 'least_tabs',
  },
  LIMITS: {
    MAX_WORKSPACES: 50,
    MAX_NOTES_LENGTH: 1000,
  },
  AI: {
    DEFAULT_PROVIDER: 'ollama',
    DEFAULT_ENDPOINT: 'http://localhost:11434',
    DEFAULT_MODEL: 'qwen3:4b',
    DEFAULT_GEMINI_MODEL: 'gemini-2.5-flash',
    DEFAULT_OPENROUTER_MODEL: 'google/gemini-2.5-flash',
    DEFAULT_GROQ_MODEL: 'llama-3.3-70b-versatile',
    TIMEOUT_MS: 60000,
    ROLLBACK_WORKSPACE_NAME: 'Original Session',
  },
  PREFERENCE_MEMORY: {
    VERSION: 2,
    ENABLED: true,
    // Learning signal weights
    SIGNAL_WORKSPACE_RENAME: 10,
    SIGNAL_WORKSPACE_EDIT: 10,
    SIGNAL_DOMAIN_MOVE: 15,
    SIGNAL_REPEAT_RENAME: 5,
    SIGNAL_WORKSPACE_MERGE: 12,
    SIGNAL_REPEAT_PATTERN: 3,
    SIGNAL_ACCEPT: 1,
    SIGNAL_RESTORE: 1,
    SIGNAL_DELETE_IMMEDIATE: -2,
    SIGNAL_REJECT_PATTERN: -5,
    LEARNING_FACTOR: 0.01,
    MAX_CORRECTIONS: 500,
    MAX_DOMAIN_RULES: 1000,
    MAX_WORKSPACE_PATTERNS: 100,
    MAX_NAMING_PREFERENCES: 200,
    INITIAL_CONFIDENCE: 0.50,
    POSITIVE_CORRECTION_BOOST: 0.05,
    CONFIRMATION_BOOST: 0.02,
    MAX_CONFIDENCE: 0.95,
    MIN_CONFIDENCE: 0.20,
    DECAY_INTERVAL_DAYS: 30,
    DECAY_FACTOR: 0.98,
    HIGH_CONFIDENCE_THRESHOLD: 0.80,
    LOW_CONFIDENCE_THRESHOLD: 0.60,
  },
};
